# Google Cloud Build configuration for MADE INFINITE
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/made-infinite-music/made-infinite:latest', 
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/made-infinite-music/made-infinite:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'made-infinite',
      '--image', 'gcr.io/made-infinite-music/made-infinite:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--memory', '8Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--max-instances', '1',
      '--min-instances', '0',
      '--allow-unauthenticated',
      '--port', '8080',
      '--set-env-vars', 'NODE_ENV=production,STORAGE_MODE=gcs,GCS_BUCKET_NAME=made-infinite-bucket-2025,ENABLE_STEM_PROCESSING=true,PYTHON_PATH=python3,STEM_PROCESSING_TIMEOUT=1800000,MAX_CONCURRENT_PROCESSING=2,ADMIN_PASSWORD=made2024'
    ]

# Use high-CPU machine for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  
# Extended timeout for downloading AI models
timeout: '3600s' 