[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'node server.js'

[variables]
NODE_ENV = 'production'
# Increase memory for large file handling
NODE_OPTIONS = '--max-old-space-size=2048' 